In [1]:
import numpy as np


In [2]:
vet = np.zeros((4,12))
vet.shape

(4, 12)

In [3]:
vet[0:13][0] = -np.arange(3, 15)[::-1]

In [4]:
vet

array([[-14., -13., -12., -11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,
         -3.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.]])

In [36]:
vet[1][:] = -np.arange(15,3,-1) + 2
vet[2][:] = -np.arange(15, 3,-1) + 3
vet[3][0] = 13

In [37]:
vet

array([[-14., -13., -12., -11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,
         -3.],
       [-13., -12., -11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,
         -2.],
       [-12., -11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,
         -1.],
       [ 13.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.]])

In [38]:
import sys
import gym
import numpy as np
from collections import defaultdict, deque
import matplotlib.pyplot as plt
%matplotlib inline

import check_test
from plot_utils import plot_values

In [39]:
Q = defaultdict(lambda: np.zeros(env.nA))

In [45]:
print(Q.keys())

dict_keys([])


In [46]:
Q

defaultdict(<function __main__.<lambda>()>, {})

In [48]:
env = gym.make('CliffWalking-v0')

In [49]:
np.zeros(env.nA)

array([0., 0., 0., 0.])

In [59]:
from collections import defaultdict, deque
avg_scores = deque(maxlen=20)
for i in range(5):
    avg_scores.append(i*2)

len(avg_scores)

5

In [60]:
lin_arr = np.linspace(0,20,len(avg_scores),endpoint=False)

In [61]:
lin_arr

array([ 0.,  4.,  8., 12., 16.])

In [63]:
lin_arr = np.linspace(0,20,len(avg_scores),endpoint=True)
lin_arr

array([ 0.,  5., 10., 15., 20.])

In [64]:
arr = [-12.8, -0.6, -3.2]
max_val = np.max(arr)
print(max_val)

-0.6
